spring.application.name=sfasystem

# DB接続設定
spring.datasource.url=jdbc:mysql://localhost:3307/sfa_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ポート設定
server.port=8081

# セッション設定
server.servlet.session.persistent=false